### ISSUE TITLE
Add more game rules to choose from for milestone 4

### ISSUE THREAD

**Issue by SamTheBlow** [SamTheBlow/grand-strategy-game#112]
Person reading this, if there are new rules you'd like to add, whether or not they're on this list, do it!

Here's an incomplete list I've written down for now:

Add money to the game
- [x] Add money as an int in Country
- [x] Save & load this new variable
- [x] Add new rule for how much money countries start with
- [x] Make the scenario give money to all countries at the start
- [x] Add a new chat command "/money" to see how much money you have
- [x] Provinces have a new int variable income_money
- [x] Save & load this new variable
- [x] Add new rule for how much income provinces give (random; constant; depending on pop size)
- [x] Make the scenario give income_money to provinces at the start
- [x] On new turn, give all countries money according to their province money incomes
- [x] On new turn, update the money income if it depends on pop size
- [x] Make chat commands show the new rules and information

Add the ability to buy a fortress
- [x] Add new rule for being able to buy fortresses
- [x] Add new rule for fortress price
- [x] Add a new chat command to buy a fortress
- [x] If no selected province, give system message
- [x] If selected province isn't yours, give system message
- [x] If not enough money, give system message
- [x] If already a fortress there, give system message
- [x] When it works, add a fortress to the selected province
- [x] When it works, reduce the country's money

Choose to have more population in starting province
- [x] Add new rule for more population in starting province
- [x] Make the scenario do it when the rule is turned on

Choose to start with a fortress
- [x] Add new rule for starting with a fortress already built
- [x] Make the scenario only do it when the rule is turned on

Add army recruitment to the game
- [x] Add new rule for enabling reinforcements on new turn
- [x] Add new rule for reinforcements size: random; constant; pop size
- [x] Add new rule for enabling manual recruitment
- [x] Add new rule for money cost per military unit
- [x] Add new rule for pop cost per military unit
