### ISSUE TITLE
Update the AI for milestone 4

### ISSUE THREAD

**Issue by SamTheBlow** [SamTheBlow/grand-strategy-game#131]
New gameplay features were added, which the AI doesn't use. The optimal strategy changed, too.

For now, there's no need for the AI to be optimal. Just make it use the new features.

===
- [x] Make the AI build fortresses
- [x] Make TestAI1 build in the most populated provinces
- [x] Make TestAI2 build in the most endangered provinces
