### ISSUE TITLE
Code refactors I want to see for milestone 4

### ISSUE THREAD

**Issue by SamTheBlow** [SamTheBlow/grand-strategy-game#81]
This is an issue in which I write down all the changes I want to make to the code.

=== EASY-ish (takes time)
- [x] Save/load code rewrite

=== MEDIUM
I'm sick of having to go change code in both json loader and scenario loader. Rewrite the scenario script so that it creates JSON data and uses the JSON loader to load the game.
- [x] Make a new class GameFromPath. It builds a game using just a file path.
- [x] Move game.gd's load_from_path to the new class GameFromPath
- [x] Make main.gd use GameFromPath to load a game from path. Don't forget to still use game.init()
- [x] Make a new class GameFromScenario. It builds a game using just a scenario scene and a GameRules object.
- [x] Move game.gd's load_from_scenario to the new class
- [x] Make main.gd use GameFromScenario to load a game from scenario.
- [x] Make the scenario class return a Dictionary (JSON data) instead of a GameState (kinda have to do the whole thing in one shot)
- [x] Make GameFromScenario take the resulting JSON data and then use GameFromJSON to load the game

=== MEDIUM
GameMediator needs to go.
- [x] Get rid of GameMediator: directly use ModifierMediator instead
- [x] Have a new function game.modifiers() to get modifiers from a game
- [x] To allow objects to provide modifiers, create a new function game.add_modifier_provider()
- [x] Pass a Game type to objects instead of ModifierMediator; make them use the two functions above
- [x] Rename ModifierMediator to ModifierRequest

=== HARD
GameState also needs to go.
- [x] Get rid of the province_selected signals and functions. Instead, Province's selected signal will directly be connected to Game's _on_province_selected during loading.
-
- [x] Move the Countries node to Game (and rewrite all classes to use game.countries instead of game_state.countries)
- [x] No longer add Countries and Country to the scene tree (it does nothing)
- [x] Make Countries not extend Node anymore
-
- [x] Move the Players node to Game
- [x] No longer add Players and Player to the scene tree (it does nothing)
- [x] Make player classes not extend Node anymore
-
- [x] Move the GameWorld node to Game
- [x] Move _check_percentage_winner and _province_count_per_country to Game
- [x] Move _on_new_turn and _on_game_over to Game
- [x] Get rid of all game_over signals. Instead, Game will have a function end_game() that takes the winner as input.
- [x] Move the GameTurn node and setup_turn function to Game
- [x] Move the GameRules to Game
- [x] Move the copy function to Game
- [x] Delete GameState

=== HARD
#120 
Armies are independent from provinces.
- [x] Save army data separately from province data
- [x] Rename Armies to ProvinceArmies
-
- [x] Use a new function army.move to move armies instead of province.armies.add_army
-
- [x] Make new class Armies to manage a game's armies; add it as a property of GameWorld
- [x] Save & load armies from & to that class
- [x] Rewrite ProvinceArmies to store & access armies using the new class
-
- [x] Move add_army and remove_army from ProvinceArmies to Armies
- [x] Move merge_armies to Armies; it takes a province as input
- [x] Move army_from_id to Armies; it takes a province as input
- [x] Move new_unique_army_id to Armies; takes province as input
- [x] Move the other two utility functions to Armies
- [x] Move the position_army_host variable back to the Province class
- [x] Delete ProvinceArmies; add armies to the scene as children of a regular Node

=== EASY (requires armies independent from provinces)
#121 
Army IDs are global
- [x] The code now checks all of the game's armies to ensure no duplicate IDs, instead of on a per province basis
- [x] Functions "army_with_id" and "new_unique_army_id" no longer take a province as input
- [x] Make the scenario give a unique ID to each generated army

=== EASY (requires global army IDs)
- [x] Armies have a province variable to directly know where they are
- [x] ActionArmyMovement and ActionArmySplit no longer need a _province_id variable

=== EASY
All hardcoded file paths must BEGONE!
- [x] Put all the scenes in export variables.
- [x] Replace all hardcoded file paths with a reference to those export variables

=== EASY
- [x] Army's """setup""" function should be renamed

=== EASY-ish
- [x] Province: determine_new_owner and auto_recruit should have their own class

=== EASY-ish
- [x] Add global modifiers array
- [x] Move global attacker/defender efficiency to global modifiers array

===
- [x] Stop hard coding the minimum army size everywhere

**Comment by SamTheBlow** [comment]
"Having the province links stored in the visual classes is probably no longer necessary, but removing them would likely require some rewriting"

**Comment by SamTheBlow** [comment]
"It's so easy to create an army node without giving it a key. It took me a while to find the culprit :("

**Comment by SamTheBlow** [comment]
"I commented out the code for setting an Army node active and the game never crashed... might want to remove that later"

**Comment by SamTheBlow** [comment]
OK, I've really tried my best to do the rewrite, and it does work! However, I'm not satisfied with the result. One big problem is that after the rewrite, the game has much worse lag spikes (not sure why). But even more importantly, I feel like after the rewrite, the game's code becomes way too fragile / difficult to maintain.

I will keep the rewritten code somewhere, but I think that before I can use it, I will have to do some more code rewrites first.

**Comment by SamTheBlow** [comment]
There are no useless variables anymore since game states are no longer a thing, but I do want to work on some of those problems written inside quotation marks. I'm going to rename this issue

**Comment by SamTheBlow** [comment]
> OK, I've really tried my best to do the rewrite, and it does work! However, I'm not satisfied with the result. One big problem is that after the rewrite, the game has much worse lag spikes (not sure why). But even more importantly, I feel like after the rewrite, the game's code becomes way too fragile / difficult to maintain.
> 
> I will keep the rewritten code somewhere, but I think that before I can use it, I will have to do some more code rewrites first.

By the way, that rewrite ended up being completely irrelevant

**Comment by SamTheBlow** [comment]
This issue doesn't make much sense to me anymore. I'm going to change it to be a list of code refactors I want to get done for milestone 4.

**Comment by SamTheBlow** [comment]
I'm done!
After all these changes, there might still be some obsolete pieces of code here and there.
I'm very happy and also a bit surprised that I was able to make all these changes in just a week.

**Comment by SamTheBlow** [comment]
I'll keep this open as I find more things I need to rework
